version: "3.3"
services:
  homer:
    image: b4bz/homer:latest
    ports:
      - 16080:8080
    container_name: homer
    user: 1000:1000
    restart: always
    volumes:
      - ./data/homer/assets/:/www/assets

  nginx:
    image: nginx:1.25.1
    container_name: nginx
    ports:
      - 16443:80

  openvscode-server:
    image: lscr.io/linuxserver/openvscode-server:latest
    container_name: openvscode-server
    env_file:
      - ./data/vscode/.env
    volumes:
      - ./data/vscode/config:/config
    ports:
      - 16022:3000
    restart: unless-stopped

volumes:
  portainer_data:
